### ISSUE TITLE
hardcode storing them in the plugin is bad

### ISSUE THREAD

**Issue by MrIvanPlays** [ArcanePlugins/MobSkullLib#5]
what if any modification is needed? it'd be probably better to pull them from a service

**Comment by lokka30** [comment]
oops, somehow missed this. not a fan of pulling them from an online source. this resource will update as Minecraft does so all plugins need to do is use the latest version of the library and they'll have all the sources. mob skull textures shouldn't change (unless a higher quality one is found for some reason).
